#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# downgrading! see this http://tickets.opscode.com/browse/COOK-1385
cookbook 'apt', :git => 'https://github.com/opscode-cookbooks/apt', :ref=>'72295f9354f0a0a791f198f4158d1f428af6e29d'
cookbook 'git'

cookbook 'python', :git => 'git://github.com/lastobelus/python.git'
cookbook 'imagemagick'

# ruby stack
cookbook 'java'
cookbook 'ruby_build', :git => 'https://github.com/fnichol/chef-ruby_build'
cookbook 'rbenv', :git => 'https://github.com/fnichol/chef-rbenv'

# nodejs stack
cookbook 'nodejs', :git => 'https://github.com/mdxp/nodejs-cookbook'
cookbook 'nodejs-support', :git => 'https://github.com/jondot/chef-nodejs-support'
cookbook 'nginx'

# statsd stack
cookbook 'graphite', :git => 'https://github.com/jondot/graphite'
cookbook 'statsd', :git => 'https://github.com/hectcastro/chef-statsd'


# redis stack
cookbook 'redis', :git => 'https://github.com/ctrabold/chef-redis'

# mongodb stack
cookbook 'mongodb', :git => 'https://github.com/edelight/chef-mongodb'


# cookbook 'chef-client'
# cookbook 'apache2', '>= 1.0.0'
# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
